apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manifests
  namespace: argocd
spec:
  project: retail-store
  source:
    repoURL: https://github.com/MomtezMdimagh/retail-store-eks-platform.git
    targetRevision: main
    path: gitops/environments/dev/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
